# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e01e735f804ea36d72cf5ef931a27f6801f516a52fc70f6d9e249b49a5af3b21bbd4ca3431f75fb403cfaf0df1a2f2ad1d6c6c8620d1603f9c4749f840b2bc

test:
  secret_key_base: 8d307a22c5d9a850b0572bb2c5140e02097524224d1aa4c8341ca5d166b4c643973caa15637ce694641f34eef0b450ed4aca2bb5eb88e62b95a9ea98596f44b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
